server:
  port: 8766

spring:
  application:
    name: service-hi
  rabbitmq:
    host: 192.168.1.141
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
sms: #自己定义数据
  ip: 127.0.0.1
