server:
  port: 8081

spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: service-hi
        uri: lb://service-hi #uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
        predicates:
          - Path=/demo/**
        filters:
          - StripPrefix=1
          - RequestTime=true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

rabbitmq:
	host: 192.168.1.141

