server:
  port: 8762

spring:
  application:
    name: service-hi
  rabbitmq:
    host: 192.168.1.141
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress：
      ip: true
  instance-id: ${spring.cloud.client.ipAddress}:${server.port}
      
sms: #自己定义数据
  ip: 127.0.0.1
